### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by edeuxk** [aidan-walden/Twitch-Rewards-Farmer#2]
Hello, thanks for the great work!

Can you explain the logic for multi accounts?

**Comment by aidan-walden** [comment]
Sure. Basically, the way it works is this:

On startup, the script will ask for the username of a Twitch account. If that username's cookies cannot be found in the current directory, you will be asked to login. Then, the cookies for that session are stored locally, so that you are already logged in the next time you start the script. The idea is to start multiple instances of the script, and have each one log in under a different user, to farm multiple Valorant keys at once (or whatever else, but this function was added b/c of Valorant)
